version: '3.8'
services: 
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABSE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  backend: 
    depends_on:
      - db
    build: ./api
    volumes:
      - ./api/:/src/api
    ports:
      - "$API_PORT:$API_PORT"
volumes:
  db_data: {}

 